service: file-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: python3.7
  stage: dev
  region: us-east-1
  memorySize: 128
  timeout: 10

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [userTable, Arn]

    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ fileTable, Arn ]

    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - "Fn::GetAtt": [ folderTable, Arn ]

  #  - Effect: Allow
  #     Action: s3:*
  #     Resource:
  #       - "arn:aws:s3:::tim19-bucket"
  #       - "arn:aws:s3:::tim19-bucket/*"
#      arn:aws:iam::439915027912:role/api-gateway-s3-role

# Packaging global configuration
package:
  # Create separate zip for each Lambda function
  individually: true
  patterns:
    # Exclude everything (each Lambda will specify which directory should be included)
    # To exclude use '!' prefix
    - '!**/**'
    # Include utility directory for every Lambda function
    - 'utility/**'

functions:
  createUser:
    handler: createUsers/create_users.create
    package:
      # Include 'createUsers' directory and all child directories
      include: 'createUsers/**'
    # Specifies events that trigger the Lambda function
    events:
      # REST API endpoint of API Gateway
      - http:
          # Path for this endpoint
          path: users
          # HTTP method for this endpoint
          method: post
          # Enable CORS. Don't forget to return the right header in your response
          cors: true

  getUsers:
    handler: getUsers/get_users.get_all
    package:
      include: 'getUsers/**'
    events:
      - http:
          path: users
          method: get
          cors: true

  getUser:
    handler: getUser/get_user.get_one
    package:
      include: 'getUser/**'
    events:
      - http:
          path: users/{username}
          method: get
          cors: true
          request:
            parameters:
              paths:
                username: true
  createFile:
    handler: createFiles/create_files.create
    package:
      include: 'createFiles/**'
    events:
      - http:
          path: files
          method: post
          cors: true
  getFiles:
    handler: getFiles/get_files.get_all
    package:
      include: 'getFiles/**'
    events:
      - http:
          path: files
          method: get
          cors: true

  getFile:
    handler: getFile/get_file.get_one
    package:
      include: 'getFile/**'
    events:
      - http:
          path: files/{id}
          method: get
          cors: true
          # Specifying path parameters
          request:
            parameters:
              paths:
                id: true
  getBucket:
    handler: getBucket/get_bucket.get_one
    package:
      include: 'getBucket/**'
    events:
      - http:
          path: bucket/{sufix}
          method: get
          cors: true
          request:
            parameters:
              paths:
                sufix: true
  getSharedBucket:
    handler: getSharedBucket/get_bucket.get_one
    package:
      include: 'getSharedBucket/**'
    events:
      - http:
          path: sharedBucket/{sufix}
          method: get
          cors: true
          request:
            parameters:
              paths:
                sufix: true
resources:
  Resources:
    userTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: userTable
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
    fileTable:
        Type: AWS::DynamoDB::Table
        Properties:
          TableName: fileTable
          AttributeDefinitions:
            - AttributeName: id
              AttributeType: S
          KeySchema:
            - AttributeName: id
              KeyType: HASH
          ProvisionedThroughput:
            ReadCapacityUnits: 1
            WriteCapacityUnits: 1

    folderTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: folderTable
        AttributeDefinitions:
          - AttributeName: username
            AttributeType: S
        KeySchema:
          - AttributeName: username
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
